<?php


namespace App\Tests;


use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class MyTest extends WebTestCase
{
    private $client;

    private $router;

    protected function setUp() : void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testMyTest()
    {
        $a = ['b' => 1];
        $this->assertTrue(true);
        return;
    }

}