version: '3'

services:
  app:
    build: ./application
    container_name: app
    restart: always
    links:
      - db
    volumes:
      - ./application:/application
      - /application/var
      - ./application/var/log:/application/var/log
      - ./application/var/cache:/application/var/cache
    ports:
    - 80:8080

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./database/data:/var/lib/mysql
    - ./database/log:/var/log/mysql